server:
  port: 9000

spring:
  profiles:
    include:
      - db
      - jwt
      - aws

jpa:
  hibernate:
    ddl-auto: none
    properties:
  properties:
    format_sql: true
    use_sql_comments: true
    default_batch_fetch_size: 500
  database: mysql
  database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace