cloud:
  aws:
    credentials:
      accessKey: AKIA5ZZC7D5TV2JGD2GE
      secretKey: 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
    s3:
      bucket: 버킷 이름
    region:
      static: ap-northeast-2
    stack:
      auto: false